apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.database.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-{{ .Values.database.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-{{ .Values.database.name }}
        app.kubernetes.io/version: "{{ .Chart.Version }}"
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.database.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.database.user }}
            - name: POSTGRESQL_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.database.name }}
          resources:
            requests:
              memory: {{ .Values.memory.requested }}
            limits:
              memory: {{ .Values.memory.limit }}
          ports:
            - name: postgres
              containerPort: {{ .Values.port }}
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          emptyDir: { }
      imagePullSecrets:
      - name: 13196395-emilgaripov-pull-secret